### ISSUE TITLE
weight uncertainty issue

### ISSUE THREAD

**Issue by xiaochenwang94** [QunBB/DeepLearning#1]
https://github.com/QunBB/DeepLearning/blob/ad4a14cfc31910bc139c2b9f5e0355aec946a088/multitasklearning/loss/uncertainty_weight.py#L18

If uncertainty_weight[i] is negative then tf.log(uncertainty_weight[i]) will be nan.

**Comment by QunBB** [comment]
Yes, you are right. We can initialize the tensor variable `log(uncertainty_weight)` rather than `uncertainty_weight` to avoid the log computation.
You could check the latest code that i has commited. [multitasklearning/loss/uncertainty_weight.py](https://github.com/QunBB/DeepLearning/blob/main/multitasklearning/loss/uncertainty_weight.py)
